import type { PostResponse, Author, Project, SiteStats, } from '@/types'


export const author: Author = {
    name: 'AdoruKw',
    avatar: 'https://picsum.photos/seed/avatar/200/200',
    bio: '一个热爱编程和游戏的开发者，正在探索像素艺术与Web开发的结合。',
    location: '中国',
    social: {
        github: 'https://github.com',
        email: 'hello@example.com'
    }
}

export const projects: Project[] = [
    {
        id: '1',
        name: 'AdoruWorld Blog',
        description: '口袋妖怪风格的像素艺术个人博客，使用Vue 3和Tailwind CSS构建。',
        tech: ['Vue 3', 'TypeScript', 'Tailwind CSS', 'Vite'],
        link: 'https://example.com',
        github: 'https://github.com',
        image: 'https://picsum.photos/seed/project-blog/600/400',
        status: 'in-progress'
    },
    {
        id: '2',
        name: 'Pixel Adventure',
        description: '一款像素风格的冒险游戏，使用Phaser 3开发。',
        tech: ['Phaser 3', 'TypeScript', 'Aseprite'],
        github: 'https://github.com',
        image: 'https://picsum.photos/seed/project-game/600/400',
        status: 'in-progress'
    },
    {
        id: '3',
        name: 'Task Manager',
        description: '一个简洁的任务管理应用，支持拖拽排序和标签分类。',
        tech: ['React', 'Node.js', 'MongoDB'],
        link: 'https://example.com',
        github: 'https://github.com',
        image: 'https://picsum.photos/seed/project-task/600/400',
        status: 'completed'
    },
    {
        id: '4',
        name: 'Weather App',
        description: '天气预报应用，支持多城市切换和天气动画效果。',
        tech: ['Vue 3', 'OpenWeather API'],
        github: 'https://github.com',
        image: 'https://picsum.photos/seed/project-weather/600/400',
        status: 'archived'
    },
    {
        id: '1',
        name: 'AdoruWorld Blog',
        description: '口袋妖怪风格的像素艺术个人博客，使用Vue 3和Tailwind CSS构建。',
        tech: ['Vue 3', 'TypeScript', 'Tailwind CSS', 'Vite'],
        link: 'https://example.com',
        github: 'https://github.com',
        image: 'https://picsum.photos/seed/project-blog/600/400',
        status: 'in-progress'
    },
    {
        id: '2',
        name: 'Pixel Adventure',
        description: '一款像素风格的冒险游戏，使用Phaser 3开发。',
        tech: ['Phaser 3', 'TypeScript', 'Aseprite'],
        link: 'https://example.com',
        github: 'https://github.com',
        image: 'https://picsum.photos/seed/project-game/600/400',
        status: 'in-progress'
    },
    {
        id: '3',
        name: 'Task Manager',
        description: '一个简洁的任务管理应用，支持拖拽排序和标签分类。',
        tech: ['React', 'Node.js', 'MongoDB'],
        link: 'https://example.com',
        github: 'https://github.com',
        image: 'https://picsum.photos/seed/project-task/600/400',
        status: 'completed'
    },
    {
        id: '4',
        name: 'Weather App',
        description: '天气预报应用，支持多城市切换和天气动画效果。',
        tech: ['Vue 3', 'OpenWeather API'],
        github: 'https://github.com',
        image: 'https://picsum.photos/seed/project-weather/600/400',
        status: 'archived'
    }
]


import type { DexEntryResponse, DexCategoryInfo, DexStatusInfo, DexStats, DexCategory, DexStatus } from '@/types'

export const dexEntries: DexEntryResponse[] = [
    {
        id: '1',
        slug: 'pokemon-horizons',
        title: '宝可梦 地平线',
        originalTitle: 'ポケットモンスター',
        coverImage: 'https://picsum.photos/seed/pokemon-anime/300/400',
        category: 'anime',
        status: 'watching',
        rating: 9,
        startDate: '2023-04-14',
        comment: '新一代宝可梦动画，莉可和罗伊的冒险故事非常精彩！',
        creator: 'OLM',
        year: 2023,
        genre: ['冒险', '奇幻']
    },
    {
        id: '2',
        slug: 'spirited-away',
        title: '千与千寻',
        originalTitle: '千と千尋の神隠し',
        coverImage: 'https://picsum.photos/seed/spirited-away/300/400',
        category: 'movie',
        status: 'completed',
        rating: 10,
        startDate: '2020-06-15',
        finishDate: '2020-06-15',
        comment: '宫崎骏的巅峰之作，每次看都有新的感悟。',
        creator: '宫崎骏',
        year: 2001,
        genre: ['奇幻', '冒险']
    },
    {
        id: '3',
        slug: 'breaking-bad',
        title: '绝命毒师',
        originalTitle: 'Breaking Bad',
        coverImage: 'https://picsum.photos/seed/breaking-bad/300/400',
        category: 'tv',
        status: 'completed',
        rating: 10,
        startDate: '2022-01-10',
        finishDate: '2022-03-20',
        comment: '神剧！人物塑造和剧情发展都堪称完美。',
        creator: 'Vince Gilligan',
        year: 2008,
        genre: ['犯罪', '剧情']
    },
    {
        id: '4',
        slug: 'pokemon-scarlet-violet',
        title: '宝可梦 朱/紫',
        originalTitle: 'ポケットモンスター・スカーレット・バイオレット',
        coverImage: 'https://pi        progress: 62,csum.photos/seed/pokemon-sv/300/400',
        category: 'game',
        status: 'completed',
        rating: 8,
        startDate: '2022-11-18',
        finishDate: '2023-02-28',
        comment: '开放世界宝可梦，虽然技术问题多但游戏性很棒！',
        creator: 'Game Freak',
        year: 2022,
        genre: ['RPG', '冒险']
    },
    {
        id: '5',
        slug: 'harry-potter-series',
        title: '哈利·波特系列',
        originalTitle: 'Harry Potter',
        coverImage: 'https://picsum.photos/seed/harry-potter/300/400',
        category: 'book',
        status: 'completed',
        rating: 10,
        startDate: '2015-06-01',
        finishDate: '2016-08-15',
        comment: '陪伴我成长的经典，魔法世界永远令人向往。',
        creator: 'J.K. Rowling',
        year: 1997,
        genre: ['奇幻', '冒险']
    },
    {
        id: '6',
        slug: 'radiohead-ok-computer',
        title: 'OK Computer',
        coverImage: 'https://picsum.photos/seed/ok-computer/300/400',
        category: 'music',
        status: 'completed',
        rating: 10,
        startDate: '2021-03-10',
        comment: 'Radiohead的巅峰之作，每一首歌都是艺术品。',
        creator: 'Radiohead',
        year: 1997,
        genre: ['另类摇滚', '艺术摇滚']
    },
    {
        id: '7',
        slug: 'elden-ring',
        title: '艾尔登法环',
        originalTitle: 'ELDEN RING',
        coverImage: 'https://picsum.photos/seed/elden-ring/300/400',
        category: 'game',
        status: 'completed',
        rating: 10,
        startDate: '2022-02-25',
        finishDate: '2022-05-15',
        comment: '宫崎英高与乔治·R·R·马丁的完美合作，年度最佳！',
        creator: 'FromSoftware',
        year: 2022,
        genre: ['动作RPG', '开放世界']
    },
    {
        id: '8',
        slug: 'your-name',
        title: '你的名字。',
        originalTitle: '君の名は。',
        coverImage: 'https://picsum.photos/seed/your-name/300/400',
        category: 'movie',
        status: 'completed',
        rating: 9,
        startDate: '2016-12-02',
        finishDate: '2016-12-02',
        comment: '新海诚的视觉盛宴，故事也很动人。',
        creator: '新海诚',
        year: 2016,
        genre: ['爱情', '奇幻']
    },
    {
        id: '9',
        slug: 'steins-gate',
        title: '命运石之门',
        originalTitle: 'STEINS;GATE',
        coverImage: 'https://picsum.photos/seed/steins-gate/300/400',
        category: 'anime',
        status: 'completed',
        rating: 10,
        startDate: '2021-07-01',
        finishDate: '2021-07-15',
        comment: '神作！前期铺垫后期爆发，剧情设计太精妙了。',
        creator: 'WHITE FOX',
        year: 2011,
        genre: ['科幻', '悬疑']
    },
    {
        id: '10',
        slug: 'zelda-totk',
        title: '塞尔达传说 王国之泪',
        originalTitle: 'ゼルダの伝説 ティアーズ オブ ザ キングダム',
        coverImage: 'https://picsum.photos/seed/zelda-totk/300/400',
        category: 'game',
        status: 'playing',
        rating: 4,
        startDate: '2023-05-12',
        comment: '旷野之息的续作，建造系统太有趣了！',
        creator: 'Nintendo',
        year: 2023,
        genre: ['动作冒险', '开放世界']
    },
    {
        id: '11',
        slug: 'dune-part2',
        title: '沙丘2',
        originalTitle: 'Dune: Part Two',
        coverImage: 'https://picsum.photos/seed/dune2/300/400',
        category: 'movie',
        status: 'completed',
        rating: 9,
        startDate: '2024-03-01',
        finishDate: '2024-03-01',
        comment: '维伦纽瓦的史诗巨作，视觉效果震撼！',
        creator: 'Denis Villeneuve',
        year: 2024,
        genre: ['科幻', '史诗']
    },
    {
        id: '12',
        slug: 'pink-floyd-dark-side',
        title: 'The Dark Side of the Moon',
        coverImage: 'https://picsum.photos/seed/dark-side/300/400',
        category: 'music',
        status: 'completed',
        rating: 10,
        startDate: '2020-05-20',
        comment: '摇滚史上最伟大的专辑之一，必须完整聆听。',
        creator: 'Pink Floyd',
        year: 1973,
        genre: ['前卫摇滚']
    },
    {
        id: '13',
        slug: 'attack-on-titan',
        title: '进击的巨人',
        originalTitle: '進撃の巨人',
        coverImage: 'https://picsum.photos/seed/aot/300/400',
        category: 'anime',
        status: 'completed',
        rating: 10,
        startDate: '2020-01-01',
        finishDate: '2023-11-04',
        comment: '史诗级作品，结局虽然争议但整体是神作。',
        creator: 'MAPPA / Wit Studio',
        year: 2013,
        genre: ['动作', '黑暗奇幻']
    },
    {
        id: '14',
        slug: 'three-body-problem',
        title: '三体',
        coverImage: 'https://picsum.photos/seed/three-body/300/400',
        category: 'book',
        status: 'completed',
        rating: 10,
        startDate: '2019-04-01',
        finishDate: '2019-06-15',
        comment: '中国科幻的巅峰之作，想象力令人震撼。',
        creator: '刘慈欣',
        year: 2008,
        genre: ['科幻']
    },
    {
        id: '15',
        slug: 'persona-5-royal',
        title: '女神异闻录5 皇家版',
        originalTitle: 'ペルソナ5 ザ・ロイヤル',
        coverImage: 'https://picsum.photos/seed/p5r/300/400',
        category: 'game',
        status: 'completed',
        rating: 10,
        startDate: '2022-08-01',
        finishDate: '2022-10-15',
        comment: 'P5天下第一！音乐、美术、剧情都是顶级。',
        creator: 'ATLUS',
        year: 2020,
        genre: ['RPG', '回合制']
    }
]
