"""add dex media relation and external url

Revision ID: 62c172623edb
Revises: 0b86049f8cb8
Create Date: 2026-08-22 17:14:24.097910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62c172623edb'
down_revision: Union[str, Sequence[str], None] = '0b86049f8cb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dex_to_media',
    sa.Column('dex_id', sa.String(), nullable=False),
    sa.Column('media_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['dex_id'], ['dex.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dex_id', 'media_id')
    )
    with op.batch_alter_table('dex', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dex', schema=None) as batch_op:
        batch_op.drop_column('external_url')

    op.drop_table('dex_to_media')
    # ### end Alembic commands ###
